- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  
- name: install repo
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
  
- name: load {{component}}.schema
    ansible.builtin.command: mongo --host mongodb.kautomation.online < /app/schema/{{component}}.js
